import { describe, expect, it } from 'bun:test';
import { serialize } from '../src/serialize.ts';

describe('serialize', () => {
	it('defaults to allow all when no options', () => {
		expect(serialize({})).toBe('User-agent: *\nAllow: /\n');
	});

	it('renders allowAll preset', () => {
		const result = serialize({ preset: 'allowAll' });
		expect(result).toBe('User-agent: *\nAllow: /\n');
	});

	it('renders disallowAll preset', () => {
		const result = serialize({ preset: 'disallowAll' });
		expect(result).toBe('User-agent: *\nDisallow: /\n');
	});

	it('renders blockAI preset with comment', () => {
		const result = serialize({ preset: 'blockAI' });
		expect(result).toContain('# Allow all crawlers by default');
		expect(result).toContain('User-agent: *\nAllow: /');
		expect(result).toContain('# Block AI/LLM training crawlers');
		expect(result).toContain('User-agent: GPTBot');
		expect(result).toContain('User-agent: ClaudeBot');
		expect(result).toContain('Disallow: /');
	});

	it('renders searchOnly preset', () => {
		const result = serialize({ preset: 'searchOnly' });
		expect(result).toContain('User-agent: *\nDisallow: /');
		expect(result).toContain('User-agent: Googlebot');
		expect(result).toContain('User-agent: Bingbot');
		expect(result).toContain('Allow: /');
	});

	it('renders custom policies', () => {
		const result = serialize({
			policies: [
				{ userAgent: '*', disallow: '/api', allow: '/' },
				{ userAgent: 'GPTBot', disallow: '/' },
			],
		});
		expect(result).toContain('User-agent: *\nDisallow: /api\nAllow: /');
		expect(result).toContain('User-agent: GPTBot\nDisallow: /');
	});

	it('merges preset + custom policies', () => {
		const result = serialize({
			preset: 'allowAll',
			policies: { userAgent: 'GPTBot', disallow: '/' },
		});
		expect(result).toContain('User-agent: *\nAllow: /');
		expect(result).toContain('User-agent: GPTBot\nDisallow: /');
	});

	it('renders sitemap directives', () => {
		const result = serialize({
			preset: 'allowAll',
			sitemap: 'https://example.com/sitemap.xml',
		});
		expect(result).toContain('Sitemap: https://example.com/sitemap.xml');
	});

	it('renders multiple sitemaps', () => {
		const result = serialize({
			preset: 'allowAll',
			sitemap: [
				'https://example.com/sitemap.xml',
				'https://example.com/sitemap-blog.xml',
			],
		});
		expect(result).toContain('Sitemap: https://example.com/sitemap.xml');
		expect(result).toContain('Sitemap: https://example.com/sitemap-blog.xml');
	});

	it('renders host directive', () => {
		const result = serialize({
			preset: 'allowAll',
			host: 'example.com',
		});
		expect(result).toContain('Host: example.com');
	});

	it('renders crawl-delay', () => {
		const result = serialize({
			policies: { userAgent: '*', allow: '/', crawlDelay: 10 },
		});
		expect(result).toContain('Crawl-delay: 10');
	});

	it('renders header comment', () => {
		const result = serialize({
			header: 'Generated by vite-robots-txt',
			preset: 'allowAll',
		});
		expect(result.startsWith('# Generated by vite-robots-txt\n')).toBe(true);
	});

	it('handles OneOrMany for disallow paths', () => {
		const result = serialize({
			policies: { userAgent: '*', disallow: ['/admin', '/api', '/private'] },
		});
		expect(result).toContain('Disallow: /admin');
		expect(result).toContain('Disallow: /api');
		expect(result).toContain('Disallow: /private');
	});

	it('handles multiple user-agents in one group', () => {
		const result = serialize({
			policies: {
				userAgent: ['Googlebot', 'Bingbot'],
				allow: '/',
			},
		});
		expect(result).toContain('User-agent: Googlebot\nUser-agent: Bingbot');
	});

	it('ends with trailing newline', () => {
		const result = serialize({});
		expect(result).toMatch(/\n$/);
	});

	it('separates sections with blank lines', () => {
		const result = serialize({
			header: 'Test',
			policies: [
				{ userAgent: '*', allow: '/' },
				{ userAgent: 'GPTBot', disallow: '/' },
			],
			sitemap: 'https://example.com/sitemap.xml',
		});
		// Header → blank → group1 → blank → group2 → blank → sitemap
		const sections = result.trim().split('\n\n');
		expect(sections).toHaveLength(4);
	});

	it('skips sitemap: true (resolved by plugin, not serialize)', () => {
		const result = serialize({ preset: 'allowAll', sitemap: true });
		expect(result).not.toContain('Sitemap:');
	});

	it('skips sitemap: false', () => {
		const result = serialize({ preset: 'allowAll', sitemap: false });
		expect(result).not.toContain('Sitemap:');
	});

	it('ignores invalid crawlDelay values', () => {
		const nan = serialize({ policies: { userAgent: '*', allow: '/', crawlDelay: NaN } });
		expect(nan).not.toContain('Crawl-delay');

		const negative = serialize({ policies: { userAgent: '*', allow: '/', crawlDelay: -1 } });
		expect(negative).not.toContain('Crawl-delay');

		const inf = serialize({ policies: { userAgent: '*', allow: '/', crawlDelay: Infinity } });
		expect(inf).not.toContain('Crawl-delay');
	});

	it('accepts crawlDelay: 0', () => {
		const result = serialize({ policies: { userAgent: '*', allow: '/', crawlDelay: 0 } });
		expect(result).toContain('Crawl-delay: 0');
	});
});
