/**
 * vite-robots-txt — Type definitions
 *
 * Robots.txt spec: https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt
 * Non-standard extensions: Crawl-delay (Bing/Yandex), Host (Yandex), Clean-param (Yandex)
 */

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

/** A single value or array of values — for ergonomic config */
type OneOrMany<T> = T | T[];

/** Known bot identifiers for type-safe presets */
type KnownBot =
	| 'Googlebot'
	| 'Googlebot-Image'
	| 'Googlebot-News'
	| 'Googlebot-Video'
	| 'Bingbot'
	| 'Slurp' // Yahoo
	| 'DuckDuckBot'
	| 'Baiduspider'
	| 'YandexBot'
	| 'facebookexternalhit'
	| 'Twitterbot'
	| 'LinkedInBot'
	| 'Applebot'
	// AI crawlers
	| 'GPTBot'
	| 'ChatGPT-User'
	| 'Claude-Web'
	| 'ClaudeBot'
	| 'Amazonbot'
	| 'anthropic-ai'
	| 'Bytespider' // TikTok/ByteDance
	| 'CCBot' // Common Crawl
	| 'Google-Extended'
	| 'PerplexityBot'
	| 'Cohere-ai'
	| 'YouBot';

/** User-agent string — known bots get autocomplete, but any string is valid */
type UserAgent = KnownBot | (string & {});

// ---------------------------------------------------------------------------
// Policy (per user-agent group)
// ---------------------------------------------------------------------------

/** Rules for one or more user-agents */
interface PolicyRule {
	/** Which user-agent(s) this rule applies to. `'*'` = all crawlers. */
	userAgent: OneOrMany<UserAgent>;

	/** Paths to allow crawling. Evaluated after disallow (more specific wins). */
	allow?: OneOrMany<string>;

	/** Paths to disallow crawling. */
	disallow?: OneOrMany<string>;

	/**
	 * Seconds between successive requests.
	 * Non-standard — supported by Bing, Yandex. Ignored by Google.
	 */
	crawlDelay?: number;

	/** Inline comments placed above this rule group */
	comment?: OneOrMany<string>;
}

// ---------------------------------------------------------------------------
// Presets
// ---------------------------------------------------------------------------

/** Built-in presets for common configurations */
type Preset =
	/** `User-agent: * \n Allow: /` */
	| 'allowAll'
	/** `User-agent: * \n Disallow: /` */
	| 'disallowAll'
	/** Block known AI/LLM training crawlers while allowing search engines */
	| 'blockAI'
	/** Allow only major search engines (Google, Bing, DuckDuckGo, Yahoo, Apple) */
	| 'searchOnly';

// ---------------------------------------------------------------------------
// Plugin options
// ---------------------------------------------------------------------------

interface RobotsTxtOptions {
	/**
	 * Start from a preset, then override with `policies`.
	 * Preset rules come first; your policies are appended.
	 *
	 * @default undefined (no preset — you define everything)
	 */
	preset?: Preset;

	/**
	 * Custom policy rules. Merged after preset rules.
	 *
	 * Shorthand: pass a single `PolicyRule` instead of an array.
	 */
	policies?: OneOrMany<PolicyRule>;

	/**
	 * Sitemap URL(s) — absolute URLs written as global `Sitemap:` directives.
	 *
	 * Set to `false` to explicitly suppress sitemap output.
	 * Set to `true` to auto-detect from `sitemap.xml` at the site root.
	 *
	 * @default undefined (no sitemap directive)
	 */
	sitemap?: OneOrMany<string> | boolean;

	/**
	 * Preferred host (Yandex `Host:` directive).
	 * Non-standard — only used by Yandex.
	 *
	 * @default undefined
	 */
	host?: string;

	/**
	 * File name to write. Almost always `robots.txt`.
	 *
	 * @default 'robots.txt'
	 */
	fileName?: string;

	/**
	 * What to do in dev/serve mode.
	 *
	 * - `'disallowAll'` — serve a `Disallow: /` robots.txt (prevent dev indexing)
	 * - `'same'` — serve the same robots.txt as build
	 * - `false` — don't serve anything in dev mode
	 *
	 * @default 'disallowAll'
	 */
	devMode?: 'disallowAll' | 'same' | false;

	/**
	 * Header comment placed at the top of the file.
	 *
	 * @example 'Generated by vite-robots-txt'
	 */
	header?: string;
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export type { KnownBot, OneOrMany, PolicyRule, Preset, RobotsTxtOptions, UserAgent };
